services:
  api1:
    build: .
    hostname: api1
    networks:
      - backend
      - payment-processor
    ports:
      - "9999:9999"
    environment:
      - PAYMENT_PROCESSOR_DEFAULT_HOST=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_HOST=http://payment-processor-fallback:8080

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true