services:
  nginx:
    image: nginx:alpine
    platform: linux/amd64
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  api1:
    build: .
    hostname: api1
    platform: linux/amd64
    depends_on:
      - db
    networks:
      - backend
      - payment-processor
    environment:
      - APP_PORT=9999
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_DB=rinha
      - PAYMENT_PROCESSOR_DEFAULT_HOST=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_HOST=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "105MB"

  api2:
    build: .
    hostname: api2
    platform: linux/amd64
    depends_on:
      - db
    networks:
      - backend
      - payment-processor
    environment:
      - APP_PORT=9999
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_DB=rinha
      - PAYMENT_PROCESSOR_DEFAULT_HOST=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_HOST=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "105MB"

  db:
    image: postgres:alpine
    hostname: db
    platform: linux/amd64
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "120MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  pgdata: {}